### ISSUE TITLE
Use /etc/cron.d instead of /etc/crontab

### ISSUE THREAD

**Issue by jlp78** [mytechguyri/POCSAG-Local-Time#1]
Great idea and works great on my pi-star with POCSAG pager as well.  The only suggestion I have is to create a file in /etc/cron.d for the cron job instead of modifying /etc/crontab.  There is a possibility that a system upgrade will deploy a new /etc/crontab and your change might get overwritten.  The syntax of files in /etc/cron.d is exactly the same as in /etc/crontab (including the username to run the cron job as).

**Comment by mytechguyri** [comment]
I actually did a code rewrite to eliminate using cron at all... now it properly calculates so it only transmits in your designated time slots, and runs as a systemd service.
