### ISSUE TITLE
After TX, hotspot does not return to IDLE.

### ISSUE THREAD

**Issue by sq8w** [mytechguyri/POCSAG-Local-Time#2]
When the hotspot finds time, unfortunately it does not return to IDLE. The dashboard still shows TX: POCSAG.
<img width="268" alt="Zrzut ekranu 2024-01-11 o 14 35 17" src="https://github.com/mytechguyri/POCSAG-Local-Time/assets/40464674/f3af9938-c844-47e8-acf5-96b3ee660031">

**Comment by mytechguyri** [comment]
I was unable to replicate this issue, but have done a complete code rewrite so that its only sending messages in your transmitters designated timeslots, and now runs as a systemd service.   Please give the current version a try.
